# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 活在低处
email: 
desc: 是一种姿态，也是一种现状。
description: # this means to ignore newlines until "baseurl:"
                        “来自山川湖海，却囿于昼夜，厨房与爱。”
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.xiebiao.com" # the base hostname & protocol for your site
twitter_username: joyrap
github_username:  xiebiao

# Build settings
markdown: kramdown
plugins:
  - jekyll-archives
layouts:
  year: year-archive
  month: month-archive
  day: day-archive
  category: category-archive
  tag: tag-archive